input_data: #Paths of the input data
    pnt_caaml_allocation: C:/Users/jille/Documents/LWD/Caaml_to_ini/data/pnt_caaml_allocation.csv

pnt_path: C:/Users/jille/Documents/LWD/Caaml_to_ini/data/smp_pntfiles_scaled

caaml_path: C:/Users/jille/Documents/LWD/Caaml_to_ini/data/caaml_files

output_data:

matching_style:

matching: cutting #you can also choose: scaling
